version: "3.9"

services:
  ethereum-testnet-rpc:
    build:
      context: ./eth-vm
      args:
        MAINNET_RPC: ${ETHEREUM_MAINNET_ARCHIVE_NODE}
        HOST: ${HOST}
        PORT: ${ETHEREUM_PORT}
        CHAIN_ID: ${ETHEREUM_CHAIN_ID}
      dockerfile: Dockerfile
    image: ethereum-testnet-rpc
    container_name: ethereum-testnet-rpc
    restart: unless-stopped
    ports:
      - ${ETHEREUM_PORT}:${ETHEREUM_PORT}

  optimism-testnet-rpc:
    build:
      context: ./eth-vm
      args:
        MAINNET_RPC: ${OPTIMISM_MAINNET_ARCHIVE_NODE}
        HOST: ${HOST}
        PORT: ${OPTIMISM_PORT}
        CHAIN_ID: ${OPTIMISM_CHAIN_ID}
      dockerfile: Dockerfile
    image: optimism-testnet-rpc
    container_name: optimism-testnet-rpc
    restart: unless-stopped
    ports:
      - ${OPTIMISM_PORT}:${OPTIMISM_PORT}

  polygon-testnet-rpc:
    build:
      context: ./eth-vm
      args:
        MAINNET_RPC: ${POLYGON_MAINNET_ARCHIVE_NODE}
        HOST: ${HOST}
        PORT: ${POLYGON_PORT}
        CHAIN_ID: ${POLYGON_CHAIN_ID}
      dockerfile: Dockerfile
    image: polygon-testnet-rpc
    container_name: polygon-testnet-rpc
    restart: unless-stopped
    ports:
      - ${POLYGON_PORT}:${POLYGON_PORT}

  arbitrum-testnet-rpc:
    build:
      context: ./eth-vm
      args:
        MAINNET_RPC: ${ARBITRUM_MAINNET_ARCHIVE_NODE}
        HOST: ${HOST}
        PORT: ${ARBITRUM_PORT}
        CHAIN_ID: ${ARBITRUM_CHAIN_ID}
      dockerfile: Dockerfile
    image: arbitrum-testnet-rpc
    container_name: arbitrum-testnet-rpc
    restart: unless-stopped
    ports:
      - ${ARBITRUM_PORT}:${ARBITRUM_PORT}
  
  faucet:
    build:
      context: ./svc
      args:
        SVC_PORT: ${SVC_PORT}
      dockerfile: Dockerfile
    image: faucet
    container_name: faucet
    restart: unless-stopped
    ports:
      - ${SVC_PORT}:${SVC_PORT}
